# docker compose file for the project with three services

version: '3.7'
services:
  hadesArtemisAdapter:
    image: ghcr.io/ls1intum/hades-artemis-adapter
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"
    networks:
      - hades
    environment:
      - API_PORT=8082
      - ARTEMIS_BASE_URL=${ARTEMIS_BASE_URL}
      - ARTEMIS_NEW_RESULT_ENDPOINT=${ARTEMIS_NEW_RESULT_ENDPOINT}
      - ARTEMIS_AUTH_TOKEN=${ARTEMIS_AUTH_TOKEN}

networks:
  hades:
