ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: hades-artemis-connector.student.k8s.aet.cit.tum.de
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: hades-artemis-connector-tls
      hosts:
        - hades-artemis-connector.student.k8s.aet.cit.tum.de

env:
  API_PORT: "8082"
  ARTEMIS_BASE_URL: "https://artemis.tum.de"
  ARTEMIS_NEW_RESULT_ENDPOINT: "api/programming/public/programming-exercises/new-result"
  ARTEMIS_AUTH_TOKEN: ""
